package dev.aige.rules.core.generator.clash

import dev.aige.rules.core.entities.ClashRule
import dev.aige.rules.provider.acl4ssr.entities.ACL4SSRFile
import dev.aige.rules.provider.blackmatrix.addBlackMatrixFileRules
import dev.aige.rules.provider.blackmatrix.entities.BlackMatrixPath

class DirectClashRuleFileGenerator : ClashRuleFileGenerator("Direct.list") {
    private val blackMatrixFilePrefix: Set<BlackMatrixPath> = setOf(
        BlackMatrixPath("BiliBili"),
        BlackMatrixPath("DiDi"),
        BlackMatrixPath("MeiTu"),
        BlackMatrixPath("Pinduoduo"),
        BlackMatrixPath("Sina"),
        BlackMatrixPath("Baidu"),
        BlackMatrixPath("360"),
        BlackMatrixPath("4399"),
        BlackMatrixPath("VipShop"),
        BlackMatrixPath("XiaoMi"),
        BlackMatrixPath("Weibo"),
        BlackMatrixPath("ByteDance"),
        BlackMatrixPath("China"),
        BlackMatrixPath("ChinaTest"),
        BlackMatrixPath("ChinaIPs"),
        BlackMatrixPath("ChinaIPs"),
        BlackMatrixPath("CCTV"),
        BlackMatrixPath("Xunlei"),
        BlackMatrixPath("Huawei"),
        BlackMatrixPath("ChinaMedia"),
        BlackMatrixPath("NetEase"),
        BlackMatrixPath("NetEaseMusic"),
        BlackMatrixPath("Youku"),
        BlackMatrixPath("TencentVideo"),
        BlackMatrixPath("iQIYI"),
        BlackMatrixPath("Douyu"),
        BlackMatrixPath("Himalaya"),
        BlackMatrixPath("Alibaba"),
        BlackMatrixPath("115"),
        BlackMatrixPath("12306"),
        BlackMatrixPath("17173"),
        BlackMatrixPath("178"),
        BlackMatrixPath("17zuoye"),
        BlackMatrixPath("36kr"),
        BlackMatrixPath("51Job"),
        BlackMatrixPath("56"),
        BlackMatrixPath("58TongCheng"),
        BlackMatrixPath("ABC"),
        BlackMatrixPath("Agora"),
        BlackMatrixPath("AliPay"),
        BlackMatrixPath("AnTianKeJi"),
        BlackMatrixPath("Anjuke"),
        BlackMatrixPath("BOC"),
        BlackMatrixPath("BOCOM"),
        BlackMatrixPath("BaiFenDian"),
        BlackMatrixPath("BaoFengYingYin"),
        BlackMatrixPath("BianFeng"),
        BlackMatrixPath("Bootcss"),
        BlackMatrixPath("CAS"),
        BlackMatrixPath("CCB"),
        BlackMatrixPath("CEB"),
        BlackMatrixPath("CGB"),
        BlackMatrixPath("CIBN"),
        BlackMatrixPath("CKJR"),
        BlackMatrixPath("CMB"),
        BlackMatrixPath("CNKI"),
        BlackMatrixPath("CNNIC"),
        BlackMatrixPath("CSDN"),
        BlackMatrixPath("AcFun"),
        BlackMatrixPath("CaiNiao"),
        BlackMatrixPath("CaiXinChuanMei"),
        BlackMatrixPath("Camera360"),
        BlackMatrixPath("ChinaMobile"),
        BlackMatrixPath("ChinaNews"),
        BlackMatrixPath("ChinaTelecom"),
        BlackMatrixPath("ChinaUnicom"),
        BlackMatrixPath("ChuangKeTie"),
        BlackMatrixPath("ChunYou"),
        BlackMatrixPath("DaMai"),
        BlackMatrixPath("DanDanZan"),
        BlackMatrixPath("Dandanplay"),
        BlackMatrixPath("DangDang"),
        BlackMatrixPath("Dedao"),
        BlackMatrixPath("Deepin"),
        BlackMatrixPath("DiSiFanShi"),
        BlackMatrixPath("DianCeWangKe"),
        BlackMatrixPath("DingTalk"),
        BlackMatrixPath("DingXiangYuan"),
        BlackMatrixPath("Domob"),
        BlackMatrixPath("DouBan"),
        BlackMatrixPath("EastMoney"),
        BlackMatrixPath("Eleme"),
        BlackMatrixPath("FanFou"),
        BlackMatrixPath("FeiZhu"),
        BlackMatrixPath("FengHuangWang"),
        BlackMatrixPath("FengXiaWangLuo"),
        BlackMatrixPath("Fiio"),
        BlackMatrixPath("Funshion"),
        BlackMatrixPath("6JianFang"),
        BlackMatrixPath("GaoDe"),
        BlackMatrixPath("GuiGuDongLi"),
        BlackMatrixPath("HaiNanHangKong"),
        BlackMatrixPath("HanYi"),
        BlackMatrixPath("HeMa"),
        BlackMatrixPath("HibyMusic"),
        BlackMatrixPath("HuYa"),
        BlackMatrixPath("HuaShuTV"),
        BlackMatrixPath("HuanJu"),
        BlackMatrixPath("HunanTV"),
        BlackMatrixPath("Hupu"),
        BlackMatrixPath("ICBC"),
        BlackMatrixPath("JiGuangTuiSong"),
        BlackMatrixPath("JianGuoYun"),
        BlackMatrixPath("JianShu"),
        BlackMatrixPath("JinJiangWenXue"),
        BlackMatrixPath("JingDong"),
        BlackMatrixPath("JueJin"),
        BlackMatrixPath("Keep"),
        BlackMatrixPath("KingSmith"),
        BlackMatrixPath("Kingsoft"),
        BlackMatrixPath("KouDaiShiShang"),
        BlackMatrixPath("Ku6"),
        BlackMatrixPath("KuKeMusic"),
        BlackMatrixPath("KuaiDi100"),
        BlackMatrixPath("KuaiShou"),
        BlackMatrixPath("KuangShi"),
        BlackMatrixPath("KugouKuwo"),
        BlackMatrixPath("LanZouYun"),
        BlackMatrixPath("LeJu"),
        BlackMatrixPath("LeTV"),
        BlackMatrixPath("Lenovo"),
        BlackMatrixPath("LuDaShi"),
        BlackMatrixPath("LvMiLianChuang"),
        BlackMatrixPath("Maocloud"),
        BlackMatrixPath("MeiTuan"),
        BlackMatrixPath("MeiZu"),
        BlackMatrixPath("MiWu"),
        BlackMatrixPath("Migu"),
        BlackMatrixPath("MingLueZhaoHui"),
        BlackMatrixPath("Mogujie"),
        BlackMatrixPath("Mojitianqi"),
        BlackMatrixPath("NGAA"),
        BlackMatrixPath("OPPO"),
        BlackMatrixPath("OnePlus"),
        BlackMatrixPath("OuPeng"),
        BlackMatrixPath("PPTV"),
        BlackMatrixPath("PSBC"),
        BlackMatrixPath("PingAn"),
        BlackMatrixPath("QiNiuYun"),
        BlackMatrixPath("QingCloud"),
        BlackMatrixPath("RuanMei"),
        BlackMatrixPath("SFExpress"),
        BlackMatrixPath("SMZDM"),
        BlackMatrixPath("ShangHaiJuXiao"),
        BlackMatrixPath("Shanling"),
        BlackMatrixPath("ShenMa"),
        BlackMatrixPath("ShiNongZhiKe"),
        BlackMatrixPath("Sohu"),
        BlackMatrixPath("SouFang"),
        BlackMatrixPath("SuNing"),
        BlackMatrixPath("SuiShiChuanMei"),
        BlackMatrixPath("TCL"),
        BlackMatrixPath("TaiKang"),
        BlackMatrixPath("TaiheMusic"),
        BlackMatrixPath("Teambition"),
        BlackMatrixPath("TianTianKanKan"),
        BlackMatrixPath("TianWeiChengXin"),
        BlackMatrixPath("TianYaForum"),
        BlackMatrixPath("TigerFintech"),
        BlackMatrixPath("TongCheng"),
        BlackMatrixPath("U17"),
        BlackMatrixPath("UC"),
        BlackMatrixPath("UCloud"),
        BlackMatrixPath("UPYun"),
        BlackMatrixPath("UnionPay"),
        BlackMatrixPath("Vancl"),
        BlackMatrixPath("Vivo"),
        BlackMatrixPath("WanMeiShiJie"),
        BlackMatrixPath("WangSuKeJi"),
        BlackMatrixPath("WangXinKeJi"),
        BlackMatrixPath("WenJuanXing"),
        BlackMatrixPath("WiFiMaster"),
        BlackMatrixPath("XiamiMusic"),
        BlackMatrixPath("XianYu"),
        BlackMatrixPath("XiaoGouKeJi"),
        BlackMatrixPath("XiaoYuanKeJi"),
        BlackMatrixPath("XieCheng"),
        BlackMatrixPath("XueErSi"),
        BlackMatrixPath("XueQiu"),
        BlackMatrixPath("YYeTs"),
        BlackMatrixPath("YiChe"),
        BlackMatrixPath("YiXiaKeJi"),
        BlackMatrixPath("YiZhiBo"),
        BlackMatrixPath("YouMengChuangXiang"),
        BlackMatrixPath("YouZan"),
        BlackMatrixPath("YuanFuDao"),
        BlackMatrixPath("YunFanJiaSu"),
        BlackMatrixPath("ZDNS"),
        BlackMatrixPath("ZhangYue"),
        BlackMatrixPath("ZhiYunZhong"),
        BlackMatrixPath("ZhongGuoShiHua"),
        BlackMatrixPath("ZhongWeiShiJi"),
        BlackMatrixPath("ZhongYuanYiShang"),
        BlackMatrixPath("ZhuanZhuan"),
        BlackMatrixPath("Hpplay"),
        BlackMatrixPath("iFlytek"),
        BlackMatrixPath("ifanr"),
        BlackMatrixPath("BaiShanYunKeJi"),
        BlackMatrixPath("DiLianWangLuo"),
        BlackMatrixPath("LianMeng"),
        BlackMatrixPath("WeiZhiYunDong"),
        BlackMatrixPath("8btc"),
        BlackMatrixPath("ChinaIPsBGP"),
        BlackMatrixPath("ChengTongWangPan"),
        BlackMatrixPath("ChinaMax"),
        BlackMatrixPath("DuoWan"),
        BlackMatrixPath("WanKaHuanJu"),
        BlackMatrixPath("ZhiYinManKe"),
        BlackMatrixPath("ChinaNoMedia"),
        BlackMatrixPath("WeChat"),
        BlackMatrixPath("WeChat"),
        BlackMatrixPath("ShiJiChaoXing"),
        BlackMatrixPath("ChinaIPs/ChinaIPsTest", "ChinaIPsTest"),
        BlackMatrixPath("QuickConnect"),
        BlackMatrixPath("WoLai"),
        BlackMatrixPath("Zhihu"),
        BlackMatrixPath("NGA"),
        BlackMatrixPath("DouYin"),
        BlackMatrixPath("XiaoHongShu"),
        BlackMatrixPath("GovCN"),
//        BlackMatrixPath("MOOMusic"),
        BlackMatrixPath("Marketing"),
        BlackMatrixPath("TapTap"),
        BlackMatrixPath("ZhongXingTongXun"),
        BlackMatrixPath("Geely"),
        BlackMatrixPath("ChinaMaxNoIP"),
        BlackMatrixPath("BaiDuTieBa"),
        BlackMatrixPath("FangZhengDianZi"),
        BlackMatrixPath("BeStore"),
        BlackMatrixPath("ChinaMaxNoMedia"),
        BlackMatrixPath("zhanqi"),
        BlackMatrixPath("Wteam"),
        BlackMatrixPath("Gitee"),
        BlackMatrixPath("Wanfang"),
        BlackMatrixPath("W3schools"),
        BlackMatrixPath("Picacg"),
        BlackMatrixPath("XingKongWuXian"),
        BlackMatrixPath("Qyyjt"),
        BlackMatrixPath("Coolapk"),
        BlackMatrixPath("3dm"),
        BlackMatrixPath("3Type"),
        BlackMatrixPath("4Paradigm"),
        BlackMatrixPath("BesTV"),
        BlackMatrixPath("CETV"),
        BlackMatrixPath("SMG"),
        BlackMatrixPath("AiQiCha"),
        BlackMatrixPath("AirChina"),
        BlackMatrixPath("aiXcoder"),
        BlackMatrixPath("Ali213"),
        BlackMatrixPath("Antutu"),
        BlackMatrixPath("Apifox"),
        BlackMatrixPath("AmazonCN"),
        // "Stripe", Stripe???
        BlackMatrixPath("BiliBili"),
        BlackMatrixPath("CCTV"),
        BlackMatrixPath("ChinaMedia"),
        BlackMatrixPath("NetEaseMusic"),
        BlackMatrixPath("Youku"),
        BlackMatrixPath("TencentVideo"),
        BlackMatrixPath("iQIYI"),
        BlackMatrixPath("Douyu"),
        BlackMatrixPath("Himalaya"),
        BlackMatrixPath("ChinaMax"),
        BlackMatrixPath("DouYin"),
//        BlackMatrixPath("MOOMusic"),
        BlackMatrixPath("zhanqi"),
        BlackMatrixPath("51nod"),
        BlackMatrixPath("BiliBili"),
        BlackMatrixPath("CCTV"),
        BlackMatrixPath("Tencent"),
        BlackMatrixPath("ChinaMedia"),
        BlackMatrixPath("NetEaseMusic"),
        BlackMatrixPath("TencentVideo"),
        BlackMatrixPath("iQIYI"),
        BlackMatrixPath("Himalaya"),
        BlackMatrixPath("DouYin"),
        BlackMatrixPath("IPTVMainland"),
        BlackMatrixPath("SteamCN"),
        BlackMatrixPath("Game/TencentLoLMobile", "TencentLoLMobile"),
        BlackMatrixPath("Game/GameDownloadCN", "GameDownloadCN"),
        BlackMatrixPath("Download"),
        BlackMatrixPath("Lan"),
        BlackMatrixPath("Direct"),
        BlackMatrixPath("DNS"),
        BlackMatrixPath("NTPService"),
        BlackMatrixPath("cloud/360Cloud", "360Cloud"),
        BlackMatrixPath("cloud/BaiduCloud", "BaiduCloud"),
        BlackMatrixPath("cloud/HuaweiCloud", "HuaweiCloud"),
        BlackMatrixPath("cloud/JingDongCloud", "JingDongCloud"),
        BlackMatrixPath("cloud/KingsoftCloud", "KingsoftCloud"),
        BlackMatrixPath("cloud/NeteaseCloud", "NeteaseCloud"),
        BlackMatrixPath("cloud/TencentCloud", "TencentCloud"),
        BlackMatrixPath("cloud/HiNet", "HiNet"),
        BlackMatrixPath("cloud/CloudCN", "CloudCN"),
        BlackMatrixPath("Atomdata"),
        BlackMatrixPath("STUN"),
        BlackMatrixPath("WeType"),
        BlackMatrixPath("GoogleFCM"),
    )
    private val acL4SSRFiles: Set<ACL4SSRFile> = setOf(
        ACL4SSRFile("58"),
        ACL4SSRFile("360"),
        ACL4SSRFile("4399"),
        ACL4SSRFile("AccelerateDirectSites"),
        ACL4SSRFile("Alibaba"),
        ACL4SSRFile("All4"),
        ACL4SSRFile("Baidu"),
        ACL4SSRFile("Bilibili"),
        ACL4SSRFile("ByteDance"),
        ACL4SSRFile("CCTV"),
        ACL4SSRFile("ChinaDNS"),
        ACL4SSRFile("ChinaNet"),
        ACL4SSRFile("ChinaOneKeyLogin"),
        ACL4SSRFile("CN"),
        ACL4SSRFile("DiDi"),
        ACL4SSRFile("Douyu"),
        ACL4SSRFile("Download"),
        ACL4SSRFile("Heytap"),
        ACL4SSRFile("HuaWei"),
        ACL4SSRFile("Iflytek"),
        ACL4SSRFile("Iqiyi"),
        ACL4SSRFile("JD"),
        ACL4SSRFile("Kingsoft"),
        ACL4SSRFile("Kuaishou"),
        ACL4SSRFile("LeTV"),
        ACL4SSRFile("Marketing"),
        ACL4SSRFile("Meitu"),
        ACL4SSRFile("MGTVTV"),
        ACL4SSRFile("MI"),
        ACL4SSRFile("MIUIPrivacy"),
        ACL4SSRFile("MOO"),
        ACL4SSRFile("NaSDDNS"),
        ACL4SSRFile("NetEase"),
        ACL4SSRFile("NetEaseMusic"),
        ACL4SSRFile("PDD"),
        ACL4SSRFile("PPTVPPLive"),
        ACL4SSRFile("PublicDirectCDN"),
        ACL4SSRFile("RemoteDesktop"),
        ACL4SSRFile("SohuSogo"),
        ACL4SSRFile("TapTap"),
        ACL4SSRFile("TeamViewer"),
        ACL4SSRFile("Tencent"),
        ACL4SSRFile("TencentLolm"),
        ACL4SSRFile("TencentVideo"),
        ACL4SSRFile("Vip"),
        ACL4SSRFile("Wechat"),
        ACL4SSRFile("Ximalaya"),
        ACL4SSRFile("Xunlei"),
        ACL4SSRFile("Youku"),
        ACL4SSRFile("GoogleCN"),
        ACL4SSRFile("GoogleCNProxyIP"),
        ACL4SSRFile("GoogleFCM"),
    )

    override suspend fun generate() = write { rules: MutableSet<ClashRule> ->
        // 读取 BlackMatrix 配置文件
        blackMatrixFilePrefix.forEach { rules.addBlackMatrixFileRules(it) }
        // 读取 ACL4SSR 配置文件
        rules.addAll(acL4SSRFiles.flatMap { it.rules })
        // 添加一些自定义的规则
        rules.add(ClashRule(ClashRule.Type.DOMAIN_KEYWORD, "qihoo"))
        rules.add(ClashRule(ClashRule.Type.DOMAIN_SUFFIX, "gangduotech.com"))
        rules.add(ClashRule(ClashRule.Type.DOMAIN_SUFFIX, "qiguangtech.cn"))
        rules.add(ClashRule(ClashRule.Type.DOMAIN_SUFFIX, "umeng.com"))
        rules.add(ClashRule(ClashRule.Type.DOMAIN_SUFFIX, "byd.com"))
        rules.add(ClashRule(ClashRule.Type.DOMAIN_SUFFIX, "jiagu.360.cn"))
        rules.add(ClashRule(ClashRule.Type.DOMAIN_SUFFIX, "claxh.aige.dev"))
        rules.add(ClashRule(ClashRule.Type.DOMAIN_SUFFIX, "jiguang.cn"))
        rules.add(ClashRule(ClashRule.Type.DOMAIN_SUFFIX, "blog.aige.dev"))
        rules.add(ClashRule(ClashRule.Type.DOMAIN_SUFFIX, "cloudfront.net"))
        rules.add(ClashRule(ClashRule.Type.DOMAIN_SUFFIX, "nineton.cn"))
        rules.add(ClashRule(ClashRule.Type.PROCESS_NAME, "360jiaguApp"))
        rules.add(ClashRule(ClashRule.Type.DST_PORT, "22"))
        rules.add(ClashRule(ClashRule.Type.DST_PORT, "9128"))
    }
}